### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data/wikidata/wikidata_wikititle2wikidata.tsv'

### ISSUE THREAD

**Issue by parisak916** [openai/deeptype#58]
Hi,

I get this issue when running:
python3 extraction/project_graph.py ${DATA_DIR}wikidata/ extraction/classifiers/type_classifier.py

Full error:
Traceback (most recent call last):
  File "extraction/project_graph.py", line 183, in <module>
    main()
  File "extraction/project_graph.py", line 93, in main
    cache=args.use_cache
  File "/Users/parisakhan/.pyenv/versions/3.6.0/lib/python3.6/site-packages/wikidata_linker_utils/type_collection.py", line 53, in __init__
    prefix=prefix
  File "/Users/parisakhan/.pyenv/versions/3.6.0/lib/python3.6/site-packages/wikidata_linker_utils/wikidata_ids.py", line 54, in load_names
    with open(path, "rt", encoding="UTF-8") as fin:
FileNotFoundError: [Errno 2] No such file or directory: 'data/wikidata/wikidata_wikititle2wikidata.tsv'

Thanks

**Comment by tbarnier** [comment]
You have to go through the pre-processing phase to generate these files
(and around 1TB disk space)
