### ISSUE TITLE
KeyError during ./extraction/full_process.sh {DATA_DIR} en

### ISSUE THREAD

**Issue by galtay** [openai/deeptype#8]
This was run yesterday if that helps narrow down the problem (i.e. wikidata dump used).  I'm happy to run with different params if that would help. 

```
./extraction/full_preprocess.sh ${DATA_DIR} en
Downloading wikidata into data/.
Will prepare language: en
Creating data directory
Done.
Downloading and preparing Wikidata:
Already compressed Wikidata
Traceback (most recent call last):
  File "extraction/get_wikiname_to_wikidata.py", line 353, in <module>
    main()
  File "extraction/get_wikiname_to_wikidata.py", line 266, in main
    prop_names2wikidata_names[prop] for prop in important_properties
  File "extraction/get_wikiname_to_wikidata.py", line 266, in <listcomp>
    prop_names2wikidata_names[prop] for prop in important_properties
KeyError: 'P31'
```

**Comment by JonathanRaiman** [comment]
Thanks -- Should now be updated (P31 is wikidata's internal name for `instance of`, previously the code used the human readable names, but nows wikidata prop names) :)

**Comment by galtay** [comment]
thanks! some great ideas in the paper, I'm excited to start training!
